## Lesson 6 - Fancy indexing and index tricks

NumPy offers more indexing facilities than regular Python sequences. In addition
to indexing by integers and slices, as we saw before, arrays can be indexed by
**arrays of integers** and **arrays of booleans**. 

In [1]:
import numpy as np

## Indexing with Arrays of Indices

Create an array of the first 12 square numbers:

In [2]:
a = np.arange(12)**2

In [3]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

Create an array of indices:

In [4]:
i = np.array([1, 1, 3, 8, 5]) 

In [5]:
i

array([1, 1, 3, 8, 5])

Now the cool part - index the elements of `a` at the positions `i`:

In [6]:
a[i]

array([ 1,  1,  9, 64, 25])

Let's try a different array of (bi-dimensional) indices:

In [7]:
j = np.array([[3, 4], [9, 7]])

In [8]:
a[j]

array([[ 9, 16],
       [81, 49]])

When the indexed array a is multidimensional, a single array of indices refers to the first dimension of a. The following example shows this behavior by converting an image of labels into a color image using a palette.

In [9]:
palette = np.array(
    [[0, 0, 0], # black
     [255, 0, 0], # red
     [0, 255, 0], # green
     [0, 0, 255], # blue
     [255, 255, 255]] # white
) 

Create an array of palette colors. e.g. 0: black, 1: red, etc.

In [10]:
image = np.array(
    [[0, 1, 2, 0 ],
     [0, 3, 4, 0 ]]
)

In [11]:
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

We can also give indexes for more than one dimension. The arrays of indices for
each dimension must have the same shape. 

In [12]:
a = np.arange(12).reshape(3,4)

In [13]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
# indices for the first dim (row) of a
i = np.array(
    [[0,1],
     [1,2]]
)

In [15]:
# indices for the second dim (column) of a
j = np.array(
    [[2,1],
     [3,1]]
)

In [16]:
# i and j must have equal shape
a[i,j]

array([[2, 5],
       [7, 9]])

To elaborate more on the `a[i,j]` part:

We are trying to create a 2 by 2 matrix from matrix `a`.

$$
\begin{bmatrix}
a[(i_1, j_1)], a[(i_1, j_2)] \\
a[(i_2, j_1)], a[(i_2, j_2)] \\
\end{bmatrix}
$$

This becomes:

$$
\begin{bmatrix}
a[(0, 2)], a[(1, 1)] \\
a[(1, 3)], a[(2, 1)] \\
\end{bmatrix}
$$

Which get resolves to:

$$
\begin{bmatrix}
2, 5 \\
7, 9 \\
\end{bmatrix}
$$

Let's try something else. Use row defined by `i`, and pick 2nd column of `a` only.

In [17]:
a[i, 2]

array([[ 2,  6],
       [ 6, 10]])

Now try something even more interesting.

In [18]:
# recall what a is
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
# recall what j is
j

array([[2, 1],
       [3, 1]])

In [20]:
# Use all 3 rows of a, and pick columns defined by j
a[:,j]

array([[[ 2,  1],
        [ 3,  1]],

       [[ 6,  5],
        [ 7,  5]],

       [[10,  9],
        [11,  9]]])

Naturally, we can put `i` and `j` in a sequence (say a list) and then do the indexing with the list. 

In [ ]:
# recall what a is
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# recall what i is
i

In [ ]:
# recall what j is
j

In [ ]:
l = a[i, j]

In [ ]:
l

However, we can not do this by putting `i` and `j` into an array, because this array will be interpreted as indexing the first dimension of `a`.

In [ ]:
s = np.array([i, j])

In [ ]:
s

In [ ]:
# This will be wrong
# a[s]

The `tuple` function will work though.

In [ ]:
tuple(s)

i.e. a two dimensional tuple. The first element is `i` (row), and second element is `j` (column).

In [ ]:
a[tuple(s)]

Cool hey?

Another common use of indexing with arrays is the search of the maximum value
of time-dependent series : 

In [ ]:
# time scale  (from 20 to 145 inclusive, 5 increments)
time = np.linspace(20, 145, 5)

In [ ]:
time

In [ ]:
# just to visualize what this is
np.sin(np.arange(20))

In [ ]:
# 4 time-dependent series
data = np.sin(np.arange(20)).reshape(5,4)

In [ ]:
data

In [ ]:
# index of the maxima for each series (column.
ind = data.argmax(axis=0) 

In [ ]:
ind

In [ ]:
# times corresponding to the maxima
time_max = time[ind]

In [ ]:
time_max

In [ ]:
# => data[ind[0],0], data[ind[1],1]...
data_max = data[ind, xrange(data.shape[1])]

In [ ]:
data_max

Note the use of `xrange()`. Seems for be mroe preferable than `range()` according to [this StackOverflow forum](http://stackoverflow.com/questions/135041/should-you-always-favor-xrange-over-range). Here is an answer by Brian I like alot:

> `range(n)` creates a list containing all the integers `0 ... n-1`. This is a problem if you do `range(1000000)`, because you'll end up with a 4MB+ list. `xrange()` deals with this by returning an object that pretends to be a list, but just works out the number needed from the index asked for, and returns that.

In [ ]:
all(data_max == data.max(axis=0))

In [ ]:
data.max(axis=0)

For simplicity, the `data.max()` will come in handy.

You can also use indexing with arrays as a target to assign to: 

In [ ]:
a = np.arange(5)

In [ ]:
a

In [ ]:
a[[1,3,4]] = 0

In [ ]:
a

However, when the list of indices contains repetitions, the assignment is done
several times, leaving behind the last value: 

In [ ]:
a = np.arange(5)

In [ ]:
a

In [ ]:
a[[0,0,2]]=[1,2,3]

In [ ]:
a

This is reasonable enough, but watch out if you want to use Python's += construct, as it may not do what you expect: 

In [ ]:
a = np.arange(5)

In [ ]:
a

In [ ]:
a[[0,0,2]]+=1

In [ ]:
a

Even though 0 occurs twice in the list of indices, the 0th element is only
incremented once. This is because Python requires "a+=1" to be equivalent to
"a=a+1". 

## Indexing with Boolean Arrays

When we index arrays with arrays of (integer) indices we are providing the list of indices to pick. 

With boolean indices the approach is different; we explicitly choose which items in the array we want and which ones we don't.

The most natural way one can think of for boolean indexing is to use boolean
arrays that have the same shape as the original array: 

In [ ]:
a = np.arange(12).reshape(3,4)

In [ ]:
a

In [ ]:
# b is a boolean with a's shape
b = a > 4

In [ ]:
b

In [ ]:
# 1d array with the selected elements
a[b]

This property can be very useful in assignments: 

In [ ]:
# All elements of 'a' higher than 4 become 0
a[b] = 0

In [ ]:
a[b] = 0

In [ ]:
a

You can look at the Mandelbrot set example to see how to use boolean indexing to
generate an image of the Mandelbrot set. 

The second way of indexing with booleans is more similar to integer indexing; for each dimension of the array we give a 1D boolean array selecting the slices we want. 

In [ ]:
a = np.arange(12).reshape(3,4)

In [ ]:
a

In [ ]:
# first dimension selection  (row)
b1 = np.array([False,True,True])

In [ ]:
# second dimension selection  (column)
b2 = np.array([True,False,True,False]) 

In [ ]:
# selecting rows
a[b1,:]

In [ ]:
a[b1]   # same thing

In [ ]:
# selecting columns
a[:,b2]

In [ ]:
a[...,b2]   # same thing

(This example below, I do not quite understand?)

In [ ]:
# a weird thing to do
a[b1,b2]

In [ ]:
s = tuple([b1,b2])

In [ ]:
s

In [ ]:
a[s]

## The ix_() function

The `ix_ function` can be used to combine different vectors so as to obtain the result for each n-uplet.

For example, if you want to compute all the `a + b*c` for all the triplets taken from each of the vectors `a`, `b` and `c`: 

In [ ]:
a = np.array([2,3,4,5])
b = np.array([8,5,4])
c = np.array([5,4,6,8,3])

In [ ]:
ax,bx,cx = np.ix_(a,b,c)

In [ ]:
ax

In [ ]:
bx

In [ ]:
cx

In [ ]:
ax.shape, bx.shape, cx.shape

In [ ]:
result = ax + bx*cx

In [ ]:
result

In [ ]:
result[3,2,4]

In [ ]:
a[3]+b[2]*c[4]

You could also implement the reduce as follows: 

In [ ]:
def ufunc_reduce(ufct, *vectors):
    vs = np.ix_(*vectors)
    r = ufct.identity
    for v in vs:
        r = ufct(r,v)
    return r

In [ ]:
ufunc_reduce(np.add,a,b,c)

The advantage of this version of reduce compared to the normal ufunc.reduce is
that it makes use of the Broadcasting Rules in order to avoid creating an argument array the size of the output times the num

** New Concepts! **

See [numpy.identity] (http://docs.scipy.org/doc/numpy/reference/generated/numpy.identity.html) to see an example of creating an identify array.

The use of the `*arg` and `**keywordargs` is explained in this [StackOverflow forum](http://stackoverflow.com/questions/4306574/python-method-function-arguments-starting-with-asterisk-and-dual-asterisk).

The function `repr()` is a Python built in function. Explained [here](https://docs.python.org/2/library/functions.html#func-repr). i.e. Return a string containing a printable representation of an object. 

In [ ]:
def printlist(*args):
    print repr(args)

In [ ]:
printlist(1, 2, 3, 4, 5) # or as many more arguments as I'd like

In [ ]:
def printdict(**kwargs):
    print repr(kwargs)

In [ ]:
printdict(john=10, jill=12, david=15)

In [ ]:
def printlistdict(self, *args, **kwargs):
    print repr(args)
    print repr(kwargs)

In [ ]:
printlistdict(1, 2, 3, 4, 5, john=10, jill=12, david=15)

## Indexing with Strings

See [RecordArrays](http://docs.scipy.org/doc/numpy/user/basics.rec.html). 

Numpy provides powerful capabilities to create arrays of structs or records. These arrays permit one to manipulate the data by the structs or by fields of the struct. A simple example will show what is meant.:

In [ ]:
x = np.zeros((2,),dtype=('i4,f4,a10'))

In [ ]:
x

In [ ]:
x[:] = [(1, 2., 'Hello'), (2, 3., "World")]

In [ ]:
x

Here we have created a one-dimensional array of length 2. Each element of this array is a record that contains three items, a 32-bit integer, a 32-bit float, and a string of length 10 or less. If we index this array at the second position we get the second record:

In [ ]:
x[1]

Conveniently, one can access any field of the array by indexing using the string that names that field. In this case the fields have received the default names ‘f0’, ‘f1’ and ‘f2’.

In [ ]:
y = x['f1']

In [ ]:
y

In [ ]:
y[:] = 2*y

In [ ]:
x

In [ ]:
y

See documentation for more on Structured arrays (aka "Record arrays").

## Conclusion

We have now completed Lesson 6 - Fancy Indexing and Index Tricks. A pretty tricky topic. Probably require revisiting later on / further studying.