## Lesson 6 - Fancy indexing and index tricks

NumPy offers more indexing facilities than regular Python sequences. In addition
to indexing by integers and slices, as we saw before, arrays can be indexed by
**arrays of integers** and **arrays of booleans**. 

In [1]:
import numpy as np

## Indexing with Arrays of Indices

Create an array of the first 12 square numbers:

In [2]:
a = np.arange(12)**2

In [3]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

Create an array of indices:

In [4]:
i = np.array([1, 1, 3, 8, 5]) 

In [5]:
i

array([1, 1, 3, 8, 5])

Now the cool part - index the elements of `a` at the positions `i`:

In [6]:
a[i]

array([ 1,  1,  9, 64, 25])

Let's try a different array of (bi-dimensional) indices:

In [7]:
j = np.array([[3, 4], [9, 7]])

In [8]:
a[j]

array([[ 9, 16],
       [81, 49]])

When the indexed array a is multidimensional, a single array of indices refers to the first dimension of a. The following example shows this behavior by converting an image of labels into a color image using a palette.

In [9]:
palette = np.array(
    [[0, 0, 0], # black
     [255, 0, 0], # red
     [0, 255, 0], # green
     [0, 0, 255], # blue
     [255, 255, 255]] # white
) 

Create an array of palette colors. e.g. 0: black, 1: red, etc.

In [10]:
image = np.array(
    [[0, 1, 2, 0 ],
     [0, 3, 4, 0 ]]
)

In [11]:
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

We can also give indexes for more than one dimension. The arrays of indices for
each dimension must have the same shape. 

In [12]:
a = np.arange(12).reshape(3,4)

In [13]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
# indices for the first dim (row) of a
i = np.array(
    [[0,1],
     [1,2]]
)

In [15]:
# indices for the second dim (column) of a
j = np.array(
    [[2,1],
     [3,1]]
)

In [16]:
# i and j must have equal shape
a[i,j]

array([[2, 5],
       [7, 9]])

To elaborate more on the `a[i,j]` part:

We are trying to create a 2 by 2 matrix from matrix `a`.

$$
\begin{bmatrix}
a[(i_1, j_1)], a[(i_1, j_2)] \\
a[(i_2, j_1)], a[(i_2, j_2)] \\
\end{bmatrix}
$$

This becomes:

$$
\begin{bmatrix}
a[(0, 2)], a[(1, 1)] \\
a[(1, 3)], a[(2, 1)] \\
\end{bmatrix}
$$

Which get resolves to:

$$
\begin{bmatrix}
2, 5 \\
7, 9 \\
\end{bmatrix}
$$

Let's try something else. Use row defined by `i`, and pick 2nd column of `a` only.

In [17]:
a[i, 2]

array([[ 2,  6],
       [ 6, 10]])

Now try something even more interesting.

In [18]:
# recall what a is
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
# recall what j is
j

array([[2, 1],
       [3, 1]])

In [20]:
# Use all 3 rows of a, and pick columns defined by j
a[:,j]

array([[[ 2,  1],
        [ 3,  1]],

       [[ 6,  5],
        [ 7,  5]],

       [[10,  9],
        [11,  9]]])

Naturally, we can put `i` and `j` in a sequence (say a list) and then do the indexing with the list. 

In [21]:
# recall what a is
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
# recall what i is
i

array([[0, 1],
       [1, 2]])

In [23]:
# recall what j is
j

array([[2, 1],
       [3, 1]])

In [24]:
l = a[i, j]

In [25]:
l

array([[2, 5],
       [7, 9]])

However, we can not do this by putting `i` and `j` into an array, because this array will be interpreted as indexing the first dimension of `a`.

In [26]:
s = np.array([i, j])

In [27]:
s

array([[[0, 1],
        [1, 2]],

       [[2, 1],
        [3, 1]]])

In [28]:
# This will be wrong
# a[s]

The `tuple` function will work though.

In [29]:
tuple(s)

(array([[0, 1],
        [1, 2]]), array([[2, 1],
        [3, 1]]))

i.e. a two dimensional tuple. The first element is `i` (row), and second element is `j` (column).

In [30]:
a[tuple(s)]

array([[2, 5],
       [7, 9]])

Cool hey?

Another common use of indexing with arrays is the search of the maximum value
of time-dependent series : 

In [31]:
# time scale  (from 20 to 145 inclusive, 5 increments)
time = np.linspace(20, 145, 5)

In [32]:
time

array([  20.  ,   51.25,   82.5 ,  113.75,  145.  ])

In [33]:
# just to visualize what this is
np.sin(np.arange(20))

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [34]:
# 4 time-dependent series
data = np.sin(np.arange(20)).reshape(5,4)

In [35]:
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [36]:
# index of the maxima for each series (column.
ind = data.argmax(axis=0) 

In [37]:
ind

array([2, 0, 3, 1], dtype=int64)

In [38]:
# times corresponding to the maxima
time_max = time[ind]

In [39]:
time_max

array([  82.5 ,   20.  ,  113.75,   51.25])

In [40]:
# => data[ind[0],0], data[ind[1],1]...
data_max = data[ind, xrange(data.shape[1])]

In [41]:
data_max

array([ 0.98935825,  0.84147098,  0.99060736,  0.6569866 ])

Note the use of `xrange()`. Seems for be mroe preferable than `range()` according to [this StackOverflow forum](http://stackoverflow.com/questions/135041/should-you-always-favor-xrange-over-range). Here is an answer by Brian I like alot:

> `range(n)` creates a list containing all the integers `0 ... n-1`. This is a problem if you do `range(1000000)`, because you'll end up with a 4MB+ list. `xrange()` deals with this by returning an object that pretends to be a list, but just works out the number needed from the index asked for, and returns that.

In [42]:
all(data_max == data.max(axis=0))

True

In [43]:
data.max(axis=0)

array([ 0.98935825,  0.84147098,  0.99060736,  0.6569866 ])

For simplicity, the `data.max()` will come in handy.

You can also use indexing with arrays as a target to assign to: 

In [44]:
a = np.arange(5)

In [45]:
a

array([0, 1, 2, 3, 4])

In [46]:
a[[1,3,4]] = 0

In [47]:
a

array([0, 0, 2, 0, 0])

However, when the list of indices contains repetitions, the assignment is done
several times, leaving behind the last value: 

In [48]:
a = np.arange(5)

In [49]:
a

array([0, 1, 2, 3, 4])

In [50]:
a[[0,0,2]]=[1,2,3]

In [51]:
a

array([2, 1, 3, 3, 4])

This is reasonable enough, but watch out if you want to use Python's += construct, as it may not do what you expect: 

In [52]:
a = np.arange(5)

In [53]:
a

array([0, 1, 2, 3, 4])

In [54]:
a[[0,0,2]]+=1

In [55]:
a

array([1, 1, 3, 3, 4])

Even though 0 occurs twice in the list of indices, the 0th element is only
incremented once. This is because Python requires "a+=1" to be equivalent to
"a=a+1". 