# Lesson 2 - the Basics

The original tutorial may be found at [this SciPy Tentative NumPy Tutorials](http://wiki.scipy.org/Tentative_NumPy_Tutorial#head-6a1bc005bd80e1b19f812e1e64e0d25d50f99fe2).

One thing I notice is that the original tutorial uses heavily syntax like:

```
from numpy import *
```

which according to the [PEP8 Style Guide](https://www.python.org/dev/peps/pep-0008/#imports) should be avoided. 

The PEP8 Style Guide recommends to use syntax like this instead as good practice:

```
import numpy as np
```

I use this IPython Notebook is to re-write the examples using the PEP8 Import Syntax.

In [1]:
import numpy as np

Contents:

- [An Example](#An-Example)
- [Array Creation](#Array-Creation)
- [Printing Arrays](#Printing-Arrays)
- [Basic Operations](#Universal-Functions)
- [Universal Functions](#Universal-Functions)
- [Indexing, Slicing and Iterating](#Indexing,-Slicing-and-Iterating)

# An Example

Original Tutorial [here](http://wiki.scipy.org/Tentative_NumPy_Tutorial#head-c5f4ceae0ab4b1313de41aba9104d0d7648e35cc)

Create an array of 15 integers ranging between 0 to 14, to a matrix (a NumPy array) of 3 rows by 5 columns. Assign this to `a`.

In [2]:
a = np.arange(15).reshape(3, 5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

What is the matrix shape in rows (1st dimension) and columns (2nd dimension)?

In [4]:
a.shape

(3L, 5L)

What is the number of dimensions? (should expect 2: one for rows, and one for columns).

In [5]:
a.ndim

2

What is the name of the data type? (should expect some form of integer type).

In [6]:
a.dtype.name

'int32'

Note that the data type is of type `int32`. i.e. 32-bit integer. i.e. 4 (=32/8) byte integer.

The `itemsize` method tells us that each element in the numpy array is of size 4 bytes each.

In [7]:
a.itemsize

4

How many elements are there in the NumPy array?

In [8]:
a.size

15

Just to confirm that `a` is a numpy array...

In [9]:
type(a)

numpy.ndarray

Create a new array and assign to `b`.

In [10]:
b = np.array([6, 7, 8])

In [11]:
b

array([6, 7, 8])

Just to confirm that `b` is a numpy array...

In [12]:
type(b)

numpy.ndarray

## Array Creation

Original Tutorials [here](http://wiki.scipy.org/Tentative_NumPy_Tutorial#head-d3f8e5fe9b903f3c3b2a5c0dfceb60d71602cf93)

There are several ways to create arrays.

For example, you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [13]:
a = np.array([2, 3, 4])

In [14]:
a

array([2, 3, 4])

In [15]:
a.dtype

dtype('int32')

In [16]:
b = np.array([1.2, 3.5, 5.1])

In [17]:
b

array([ 1.2,  3.5,  5.1])

In [18]:
b.dtype

dtype('float64')

A frequent error consists in calling array with multiple numeric arguments, rather than providing a single list of numbers as an argument.

In [19]:
# a = np.array(1, 2, 3, 4)    # WRONG

In [20]:
a = np.array([1, 2, 3, 4])  # RIGHT

In [21]:
a

array([1, 2, 3, 4])

`array` transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [22]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])

In [23]:
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

The type of the array can also be explicitly specified at creation time:

In [24]:
c = np.array([[1, 2], [3, 4]], dtype=complex)

In [25]:
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

Create a 3 (rows) by 4 (columns) NumPy array filled with zeros.

In [26]:
np.zeros((3, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

Create a 3 (rows) by 4 (columns) NumPy array filled with ones.

In [27]:
np.ones((3, 4)) 

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

Create a 2 (outter-most) by 3 by 4 (inner-most) NumPy array filled with ones. Set element data type to `int16`.

In [28]:
np.ones((2, 3, 4), dtype=np.int16) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

Create a 2 by 3 empty NumPy Array.

In [29]:
np.empty((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

## Printing Arrays

Original Tutorials [here](http://wiki.scipy.org/Tentative_NumPy_Tutorial#head-a476da892560e3bf994ec9b363e169b6467cd5a4)

When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:

- the last axis is printed from left to right.
- the second-to-last is printed from top to bottom.
- the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.

Create a 1D array.

In [30]:
a = np.arange(6)

In [31]:
print a

[0 1 2 3 4 5]


Create a 2D array.

In [32]:
b = np.arange(12).reshape(4, 3)

In [33]:
print b

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Create a 3D array.

In [34]:
c = np.arange(24).reshape(2, 3, 4) 

In [35]:
print c

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


Create a 4D array.

In [36]:
d = np.arange(120).reshape(2, 3, 4, 5) 

In [37]:
print d

[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]


If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners.

What is the current print option? (note the threshold input)

In [38]:
np.get_printoptions()

{'edgeitems': 3,
 'formatter': None,
 'infstr': 'inf',
 'linewidth': 75,
 'nanstr': 'nan',
 'precision': 8,
 'suppress': False,
 'threshold': 1000}

Let's try to print something.

In [39]:
print np.arange(10000)

[   0    1    2 ..., 9997 9998 9999]


In [40]:
print np.arange(10000).reshape(100,100)

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


To disable this behaviour and force NumPy to print the entire array, you can change the printing options using set_printoptions.

In [41]:
np.set_printoptions(threshold='nan')

In [42]:
print np.arange(10000)

[   0    1    2    3    4    5    6    7    8    9   10   11   12   13   14
   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29
   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44
   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59
   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74
   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89
   90   91   92   93   94   95   96   97   98   99  100  101  102  103  104
  105  106  107  108  109  110  111  112  113  114  115  116  117  118  119
  120  121  122  123  124  125  126  127  128  129  130  131  132  133  134
  135  136  137  138  139  140  141  142  143  144  145  146  147  148  149
  150  151  152  153  154  155  156  157  158  159  160  161  162  163  164
  165  166  167  168  169  170  171  172  173  174  175  176  177  178  179
  180  181  182  183  184  185  186  187  188  189  190  191  192  193  194
  195  196  

Depending on where you view the content, the above output may be framed (In IPython Notebook, this would be a small window where you get to scroll up and down), or display-all (In GitHub, it reders the entire output).

Let's view current print options and reset to previous stage.

In [43]:
np.get_printoptions()

{'edgeitems': 3,
 'formatter': None,
 'infstr': 'inf',
 'linewidth': 75,
 'nanstr': 'nan',
 'precision': 8,
 'suppress': False,
 'threshold': 'nan'}

In [44]:
np.set_printoptions(threshold=1000)

In [45]:
np.get_printoptions()

{'edgeitems': 3,
 'formatter': None,
 'infstr': 'inf',
 'linewidth': 75,
 'nanstr': 'nan',
 'precision': 8,
 'suppress': False,
 'threshold': 1000}

Let's try it out!

In [46]:
print np.arange(10000)

[   0    1    2 ..., 9997 9998 9999]


## Basic Operations

Original Tutorials [here](http://wiki.scipy.org/Tentative_NumPy_Tutorial#head-4c1d53fe504adc97baf27b65513b4b97586a4fc5)

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [47]:
a = np.array([20, 30, 40, 50])

In [48]:
a

array([20, 30, 40, 50])

In [49]:
b = np.arange(4)

In [50]:
b

array([0, 1, 2, 3])

In [51]:
c = a - b

In [52]:
c

array([20, 29, 38, 47])

In [53]:
b**2

array([0, 1, 4, 9])

In [54]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [55]:
a < 35

array([ True,  True, False, False], dtype=bool)

Unlike in many matrix languages, the product operator `*` operates elementwise in NumPy arrays. The matrix product can be performed using the `dot` function or creating matrix objects (see matrix section of this tutorial).

In [56]:
matrixA = np.array([[1, 1],
                    [0, 1]])

In [57]:
matrixB = np.array([[2, 0],
                    [3, 4]])

Elementwise product:

In [58]:
matrixA * matrixB

array([[2, 0],
       [0, 4]])

Matrix product:

In [59]:
np.dot(matrixA, matrixB)

array([[5, 4],
       [3, 4]])

Some operations, such as `+=` and `*=`, act in place to modify an existing array rather than create a new one.

In [60]:
a = np.ones((2, 3), dtype=np.int)

In [61]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [62]:
a.dtype.name

'int32'

In [63]:
b = np.random.random((2, 3))

In [64]:
b

array([[ 0.70350101,  0.34975609,  0.08133305],
       [ 0.14582757,  0.56570901,  0.5837982 ]])

In [65]:
b.dtype.name

'float64'

In [66]:
a *= 3

In [67]:
a

array([[3, 3, 3],
       [3, 3, 3]])

Add `b` (float64  type) to `a` ( int32 type). To make this possible, during the computation phase, `b` is lowered temporarily to in32 type, add to `a`. The eventual `b` type is unchanged.

In [68]:
a += b

In [69]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [70]:
a.dtype.name

'int32'

In [71]:
b.dtype.name

'float64'

Let's try the other way round.

In [72]:
b += a

In [73]:
b.dtype.name

'float64'

In [74]:
a.dtype.name

'int32'

Note that the type of `a` and `b` are unchanged.

When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

In [75]:
a = np.ones(3, dtype=np.int32)

In [76]:
a

array([1, 1, 1])

In [77]:
b = np.linspace(0, np.pi, 3)

In [78]:
b

array([ 0.        ,  1.57079633,  3.14159265])

In [79]:
a.dtype.name

'int32'

In [80]:
b.dtype.name

'float64'

In [81]:
c = a + b

In [82]:
c

array([ 1.        ,  2.57079633,  4.14159265])

In [83]:
c.dtype.name

'float64'

In [84]:
c

array([ 1.        ,  2.57079633,  4.14159265])

In [85]:
d = np.exp(c*1j)

In [86]:
c*1j

array([ 0.+1.j        ,  0.+2.57079633j,  0.+4.14159265j])

In [87]:
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [88]:
d.dtype.name

'complex128'

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the `ndarray` class.

In [89]:
a = np.random.random((2,3))

In [90]:
a

array([[ 0.52023631,  0.48638659,  0.60497732],
       [ 0.14733248,  0.787754  ,  0.24119447]])

In [91]:
a.sum()

2.7878811630921634

In [92]:
a.min()

0.14733247785821324

In [93]:
a.max()

0.78775399852425776

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array:

In [94]:
b = np.arange(12).reshape(3,4)

In [95]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Compute sum of each column (the inner nest is axis 0):

In [96]:
b.sum(axis=0)

array([12, 15, 18, 21])

Compute sum of each row (the next outer nest):

In [97]:
b.sum(axis=1)

array([ 6, 22, 38])

Compute min of each row

In [98]:
b.min(axis=1) 

array([0, 4, 8])

Compute cummulative sum along each row:

In [99]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

## Universal Functions

Original Tutorials [here](http://wiki.scipy.org/Tentative_NumPy_Tutorial#head-053463ac1c1df8d47f8723f470b62c4bd0d11f07)

NumPy provides familiar mathematical functions such as `sin`, `cos`, and `exp`. In NumPy, these are called "universal functions"(`ufunc`). Within NumPy, these functions operate elementwise on an array, producing an array as output.

See the [NumPy Example List](http://wiki.scipy.org/Numpy_Example_List) for a more comprehensive list of NumPy Universal Functions.

In [100]:
b = np.arange(3)

In [101]:
b

array([0, 1, 2])

In [102]:
np.exp(b)

array([ 1.        ,  2.71828183,  7.3890561 ])

In [103]:
np.sqrt(b)

array([ 0.        ,  1.        ,  1.41421356])

In [104]:
c = np.array((2., -1., 4.))

In [105]:
c

array([ 2., -1.,  4.])

In [106]:
np.add(b, c)

array([ 2.,  0.,  6.])

## Indexing, Slicing and Iterating

Original Tutorials [here](http://wiki.scipy.org/Tentative_NumPy_Tutorial#head-864862d3f2bb4c32f04260fac61eb4ef34788c4c)

**One-dimensional** arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [107]:
a = np.arange(10.)**3

In [108]:
a

array([   0.,    1.,    8.,   27.,   64.,  125.,  216.,  343.,  512.,  729.])

Grab element at position 2:

In [109]:
a[2]

8.0

Grab elements within the asymetric range `[2:5]`  (include elements at position 2, 3, 4 ; exclude 5)

In [110]:
a[2:5]

array([  8.,  27.,  64.])

Grab elements within the asymetric range `[:6]` with step `2` (Include elements at position 0, 2, 4; exclude anything from 6 upwards.)

In [111]:
a[:6:2]

array([  0.,   8.,  64.])

Let's replace some individual elements with new values:

In [112]:
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000

In [113]:
a

array([-1000.,     1., -1000.,    27., -1000.,   125.,   216.,   343.,
         512.,   729.])

Reverse `a`. This [blog post](http://mathalope.co.uk/2015/04/04/udacity-intro-to-computer-science-python-reverse-a-string-in-one-liner-and-test-for-palindromes/) might come in handy.

In [114]:
a[::-1] 

array([  729.,   512.,   343.,   216.,   125., -1000.,    27., -1000.,
           1., -1000.])

Let's print the cube root (i.e. power of `1/3`) of each element in the NumPy array. the root of any 

In [115]:
a

array([-1000.,     1., -1000.,    27., -1000.,   125.,   216.,   343.,
         512.,   729.])

In [116]:
for i in a:
    print i**(1/3.)

nan
1.0
nan
3.0
nan
5.0
6.0
7.0
8.0
9.0


C:\Users\Johnny\Anaconda\lib\site-packages\IPython\kernel\__main__.py:2: RuntimeWarning: invalid value encountered in double_scalars
  from IPython.kernel.zmq import kernelapp as app


**When using fractional power against a negative base number...**

Note: I am not quite sure why it does not compute the cube root of -1000., which should work out to be -0.999 ish. i.e. Cube root of `-1000` seems to work in the basic case, like this:

In [117]:
-10.**3.

-1000.0

In [118]:
-1000**(1/3.)

-9.999999999999998

This does not seem to work against a NumPy array element. Strange?

In [119]:
a = np.array([-1000.])

In [120]:
a

array([-1000.])

In [121]:
a[0]

-1000.0

In [122]:
a[0]**(1/3.)

C:\Users\Johnny\Anaconda\lib\site-packages\IPython\kernel\__main__.py:1: RuntimeWarning: invalid value encountered in double_scalars
  if __name__ == '__main__':


nan

Likewise in a for loop, no luck neither.

In [123]:
for i in a:
    print i**(1/3.)

nan


C:\Users\Johnny\Anaconda\lib\site-packages\IPython\kernel\__main__.py:2: RuntimeWarning: invalid value encountered in double_scalars
  from IPython.kernel.zmq import kernelapp as app


Have just found the solution from [this forum post](http://scipy-user.10969.n7.nabble.com/numpy-array-root-operation-td1727.html). It looks like for fractional power, some special treatment may be required.

In [124]:
x = np.array([-81,25])

In [125]:
x

array([-81,  25])

In [126]:
xRoot5 = np.sign(x) * np.absolute(x)**(1.0/5.0)

In [127]:
xRoot5

array([-2.40822469,  1.90365394])

In [128]:
xRoot5**5

array([-81.,  25.])

There is also an alternative solution using the `math` module, obtained from [this StackOverflow post](http://stackoverflow.com/questions/1361740/cubic-root-of-the-negative-number-on-python/30122775#30122775).

In [129]:
import math

In [130]:
def myPower(base, power):
    if base > 0:
        return math.pow(base, float(power))
    elif base < 0:
        return -math.pow(abs(base), float(power))
    else:
        return 0

In [131]:
myPower(-3, (1./3.))

-1.4422495703074083

**Multidimensional arrays** can have one index per axis. These indices are given in a tuple separated by commas:

In [132]:
def f(x,y):
    return 10*x + y

In [133]:
f

<function __main__.f>

Use the NumPy [fromfunction](http://docs.scipy.org/doc/numpy/reference/generated/numpy.fromfunction.html) to construct an array.

In [134]:
b = np.fromfunction(f, (5, 4), dtype=np.int)

In [135]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

We index an element from outer to inner nest.

In [136]:
b[2,3]

23

In [137]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [138]:
b[:,1]

array([ 1, 11, 21, 31, 41])

In [139]:
b[1:3,:]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

When fewer indices are provided than the number of axes, the missing indices are considered complete slices:

the last row. Equivalent to b[-1,:]

In [140]:
b[-1]

array([40, 41, 42, 43])

The expression within brackets in b[i] is treated as an i followed by as many instances of : as needed to represent the remaining axes. NumPy also allows you to write this using dots as `b[i,...]`.

The **dots**(...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is a rank 5 array (i.e., it has 5 axes), then

- `x[1,2,...]` is equivalent to `x[1,2,:,:,:]`,
- `x[...,3]` to `x[:,:,:,:,3]` and
- `x[4,...,5,:]` to `x[4,:,:,5,:]`

In [141]:
 c = np.array([[[ 0,  1,  2],
                [10, 12, 13]],
             
               [[100, 101, 102],
                [110, 112, 113]]])

In [142]:
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [143]:
c.shape

(2L, 2L, 3L)

In [144]:
c[1,...]

array([[100, 101, 102],
       [110, 112, 113]])

In [145]:
c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [146]:
c[1,:,:]

array([[100, 101, 102],
       [110, 112, 113]])

In [147]:
c[...,2]

array([[  2,  13],
       [102, 113]])

In [148]:
c[:,:,2]

array([[  2,  13],
       [102, 113]])

Iterating over multidimensional arrays is done with respect to the first axis:

In [149]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [150]:
for row in b:
    print row

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


However, if one wants to perform an operation on each element in the array, one can use the `flat` attribute which is an iterator over all the elements of the array (from inner nest to outer):

In [151]:
for element in b.flat:
    print element

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


# Conclusion

We have now completed the [Tentative NumPy Tutorials: Lesson 2 - Basics](http://wiki.scipy.org/Tentative_NumPy_Tutorial#head-6a1bc005bd80e1b19f812e1e64e0d25d50f99fe2).