# Linear Algebra

Original Tutorial may be found [here](http://wiki.scipy.org/Tentative_NumPy_Tutorial).

In [1]:
import numpy as np

This Tutorial will use also the Linear Algebra (`linalg`) sub-module (sitting inside `numpy`).

Refer to the [](http://docs.scipy.org/doc/numpy/reference/routines.linalg.html) for full `numpy.linalg` utilities.

## Simple Array Operations

In [2]:
a = np.array([[1.0, 2.0],
              [3.0, 4.0]])

In [3]:
a

array([[ 1.,  2.],
       [ 3.,  4.]])

In [4]:
a.transpose()

array([[ 1.,  3.],
       [ 2.,  4.]])

In [5]:
a

array([[ 1.,  2.],
       [ 3.,  4.]])

Compute the inverse. This [MathIsFun.com](http://www.mathsisfun.com/algebra/matrix-inverse.html) article provides some excellent examples in explaining inverse of a matrix.

In [6]:
a_inv = np.linalg.inv(a)

In [7]:
a_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

We know that, multiplying (dot multiplication) a matrix and its inverse gives us an identify matrix (see the MathIsFun.com website!).

In [8]:
np.dot(a, a_inv)

array([[  1.00000000e+00,   1.11022302e-16],
       [  0.00000000e+00,   1.00000000e+00]])

See? :)

In [9]:
u = np.eye(2) # unit 2x2 matrix; "eye" represents "I"  (Identify Matrix)

In [10]:
u

array([[ 1.,  0.],
       [ 0.,  1.]])

In [11]:
j = np.array([[0.0, -1.0],
              [1.0, 0.0]])

In [12]:
j

array([[ 0., -1.],
       [ 1.,  0.]])

In [13]:
np.dot(j, j) # matrix product

array([[-1.,  0.],
       [ 0., -1.]])

Use the `trace()` function to return the sum along the diagonals of the array. See [this NumPy Doc](http://docs.scipy.org/doc/numpy/reference/generated/numpy.trace.html#numpy.trace). 

In [14]:
np.trace(u) # trace

2.0

Say we have three matrices:

```
ax = y
```

in which `a` and `y` are known.

We want to solve `x`.

In [15]:
a = np.array([[1.0, 2.0],
              [3.0, 4.0]])

In [16]:
y = np.array([[5.], [7.]])

In [17]:
a

array([[ 1.,  2.],
       [ 3.,  4.]])

In [18]:
y

array([[ 5.],
       [ 7.]])

In [19]:
x = np.linalg.solve(a, y)

In [20]:
x

array([[-3.],
       [ 4.]])

To prove that this is correct, this must be true:

```
ax = y
```

In [21]:
s = (np.dot(a,x) == y)

In [22]:
s

array([[ True],
       [ True]], dtype=bool)

In [23]:
s.all()

True

Or just visualize it:

In [24]:
np.dot(a,x)

array([[ 5.],
       [ 7.]])

In [25]:
y

array([[ 5.],
       [ 7.]])

It certain looks like:

```
ax = y
```

Now, eigenvalue...

In [26]:
j

array([[ 0., -1.],
       [ 1.,  0.]])

In [27]:
np.linalg.eig(j)

(array([ 0.+1.j,  0.-1.j]),
 array([[ 0.70710678+0.j        ,  0.70710678-0.j        ],
        [ 0.00000000-0.70710678j,  0.00000000+0.70710678j]]))

See [this article](http://www.sosmath.com/matrix/eigen0/eigen0.html) to learn more about eigenvalue and eigenvector.