# Lesson 3 - Shape Manipulation

The Original Tutorial may be found [here](http://wiki.scipy.org/Tentative_NumPy_Tutorial#head-62ef2d3c0a5b4b7d6fdc48e4a60fe48b1ffe5006).

In [1]:
import numpy as np

## Changing the shape of an array

The Original Tutorial may be found [here](http://wiki.scipy.org/Tentative_NumPy_Tutorial#head-1ddf70136d56cfa02b4ce306264ed13398327f25)

An array has a shape given by the number of elements along each axis:

In [5]:
a = np.floor(10*np.random.random((3,4)))

In [6]:
a

array([[ 3.,  6.,  5.,  5.],
       [ 1.,  6.,  1.,  6.],
       [ 0.,  5.,  2.,  2.]])

In [7]:
a.shape

(3L, 4L)

The shape of an array can be changed with various commands:

In [8]:
a.ravel() # flatten the array

array([ 3.,  6.,  5.,  5.,  1.,  6.,  1.,  6.,  0.,  5.,  2.,  2.])

In [12]:
a.shape = (6, 2)

In [13]:
a

array([[ 3.,  6.],
       [ 5.,  5.],
       [ 1.,  6.],
       [ 1.,  6.],
       [ 0.,  5.],
       [ 2.,  2.]])

In [14]:
a.transpose()

array([[ 3.,  5.,  1.,  1.,  0.,  2.],
       [ 6.,  5.,  6.,  6.,  5.,  2.]])

The `reshape` (non-mutative) method returns its argument with a modified shape, whereas the `resize` (mutative) method modifies the array itself:

In [15]:
a

array([[ 3.,  6.],
       [ 5.,  5.],
       [ 1.,  6.],
       [ 1.,  6.],
       [ 0.,  5.],
       [ 2.,  2.]])

In [39]:
b = a.resize((2,6))

In [42]:
a

array([[ 3.,  6.,  5.,  5.,  1.,  6.],
       [ 1.,  6.,  0.,  5.,  2.,  2.]])

In [43]:
b

Note that the `resize` method has mutated `a`. It does not return anything. It just mutate (a side effect).

If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:

In [44]:
b = a.reshape(3,-1)

In [46]:
a

array([[ 3.,  6.,  5.,  5.,  1.,  6.],
       [ 1.,  6.,  0.,  5.,  2.,  2.]])

In [47]:
b

array([[ 3.,  6.,  5.,  5.],
       [ 1.,  6.,  1.,  6.],
       [ 0.,  5.,  2.,  2.]])

Note that the `reshape` method does not mutate `a`. It merely return the reshaped array.

## Stacking together different arrays

The Original Tutorial may be found [here](http://wiki.scipy.org/Tentative_NumPy_Tutorial#head-2dbfc93288ea06a02f270f2f9e6930ffbdd78b87)

In [73]:
a = np.floor(10*np.random.random((2,2)))

In [74]:
a

array([[ 1.,  9.],
       [ 7.,  7.]])

In [75]:
b = np.floor(10*np.random.random((2,2)))

In [76]:
b

array([[ 9.,  5.],
       [ 4.,  1.]])

In [77]:
np.vstack((a, b))

array([[ 1.,  9.],
       [ 7.,  7.],
       [ 9.,  5.],
       [ 4.,  1.]])

In [78]:
np.hstack((a, b))

array([[ 1.,  9.,  9.,  5.],
       [ 7.,  7.,  4.,  1.]])

The function `column_stack` stacks 1D arrays as columns into a 2D array. It is equivalent to `vstack` only for 1D arrays:

In [79]:
np.column_stack((a,b))   # With 2D arrays

array([[ 1.,  9.,  9.,  5.],
       [ 7.,  7.,  4.,  1.]])

Let's create two 1D arrays.

In [80]:
a = np.array((4., 2.))

In [81]:
b = np.array((2., 8.))

This is to quickly illustrate using the `newaxis` argument to increase a dimension for the array.

In [82]:
a[:,np.newaxis]

array([[ 4.],
       [ 2.]])

In [83]:
b[:,np.newaxis]

array([[ 2.],
       [ 8.]])

Let's `column_stack` them!

In [84]:
np.column_stack((a[:, np.newaxis], b[:, np.newaxis]))

array([[ 4.,  2.],
       [ 2.,  8.]])

In [67]:
np.vstack((a[:, np.newaxis], b[:, np.newaxis]))   # The behavior of vstack is different

array([[ 4.],
       [ 2.],
       [ 2.],
       [ 8.]])

let's try `concatenate`:

In [68]:
a

array([ 4.,  2.])

In [69]:
b

array([ 2.,  8.])

In [70]:
np.concatenate((a, b))

array([ 4.,  2.,  2.,  8.])

Sort of similar to column stack.

let's try to create array using the `r_[]` and `c_[]`

In [87]:
np.r_[1:4, 0, 4]

array([1, 2, 3, 0, 4])

In [89]:
np.c_[1:4, 2:5]

array([[1, 2],
       [2, 3],
       [3, 4]])

# Splitting one array into serveral smaller ones